//! Audit log types — `AuditEvent` and `AuditFilter`.
//!
//! Used by the `StateStore` trait's audit methods and the
//! `src/api/audit.rs::record` helper. See
//! `docs/superpowers/specs/2026-05-21-audit-log-design.md`.

use serde::{Deserialize, Serialize};

/// One row in the append-only audit log. Recorded at handler exit
/// for every state-changing API action.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[allow(dead_code)]
pub struct AuditEvent {
    /// UUID v4. Generated by the backend on write — the caller's
    /// value (if any) is ignored.
    pub id: String,

    /// RFC3339 timestamp at the moment of write.
    pub timestamp: String,

    /// Dotted action label. Currently one of:
    ///   "flow.run.start", "flow.run.abort", "flow.run.delete",
    ///   "conversation.start", "conversation.delete".
    pub action: String,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flow_path: Option<String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_ip: Option<String>,

    pub success: bool,
    pub status_code: u16,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

/// Filter for `list_audit_events` / `count_audit_events`. All fields
/// are AND-composed; unset fields match anything.
#[derive(Debug, Clone, Default, Deserialize)]
#[allow(dead_code)]
pub struct AuditFilter {
    pub flow_path: Option<String>,
    pub action: Option<String>,
    pub actor: Option<String>,
    pub since: Option<String>,
    pub until: Option<String>,
    pub success: Option<bool>,
}

impl AuditFilter {
    /// True when `event` matches every active dimension of the filter.
    #[allow(dead_code)]
    pub fn matches(&self, event: &AuditEvent) -> bool {
        if let Some(ref f) = self.flow_path
            && event.flow_path.as_deref() != Some(f.as_str())
        {
            return false;
        }
        if let Some(ref a) = self.action
            && &event.action != a
        {
            return false;
        }
        if let Some(ref a) = self.actor
            && event.actor.as_deref() != Some(a.as_str())
        {
            return false;
        }
        if let Some(ref s) = self.since
            && event.timestamp.as_str() < s.as_str()
        {
            return false;
        }
        if let Some(ref u) = self.until
            && event.timestamp.as_str() >= u.as_str()
        {
            return false;
        }
        if let Some(s) = self.success
            && event.success != s
        {
            return false;
        }
        true
    }
}
